import Foundation
import WebKit

/// Runs the bundled legibility engine and hands back the article it found.
///
/// legibility is a Rust extractor compiled to WebAssembly and inlined into one
/// self-contained page, `Legibility.html` (generated by
/// `tools/build-legibility.sh` from the commit in `tools/legibility.pin`). This
/// class owns one offscreen `WKWebView` holding that page and calls
/// `window.legibility.extract(html)` on it. WebKit runs WebAssembly normally —
/// the iOS JIT restriction does not apply inside it — so this needs no
/// `xcframework`, no C ABI, and no second Swift package.
///
/// Two properties of that page are load-bearing:
///
/// - Its own Content-Security-Policy is `default-src 'none'` with no
///   `connect-src`, so the page cannot fetch, XHR, or open a socket. An article
///   is attacker-controlled markup and this is where it is parsed; the page it is
///   parsed in can do nothing at all.
/// - It takes an HTML **string**, not a live DOM. Callers load the real page in
///   their own web view first (so script-rendered content exists), serialize it,
///   and pass the string here. Injecting the module into the article's own page
///   instead is not an option: most sites' CSP forbids `wasm-unsafe-eval`.
@MainActor
public final class LegibilityEngine {
    public static let shared = LegibilityEngine()

    public init() {}

    /// What the engine made of a document.
    public enum Outcome: Sendable {
        /// An article (or a link submission) came out of the page.
        case article(Extraction)
        /// The engine ran and found nothing extractable. `reason` is legibility's
        /// own verdict (`IndexPage`, `CommentsOnly`, `NoTextContent`,
        /// `LowConfidence`, `TooFewCompetitors`) when it gave one.
        ///
        /// Not a failure the caller should retry: the engine looked, and this is
        /// the answer.
        case noArticle(reason: String?)
        /// The engine itself could not run — the resource is missing, the page
        /// failed to load, the module trapped, or the call timed out. The caller
        /// should fall back to the other parser rather than tell the reader the
        /// page has no article in it.
        case unavailable
    }

    /// The article, projected down to what Nook's reader actually renders.
    public struct Extraction: Sendable {
        /// Sanitized article markup, ready to insert as HTML. Empty when
        /// `isLinkOnly`, where `linkURL` is the payload instead.
        public var html: String
        /// Plain text of the article body, for length checks.
        public var text: String
        /// The page's title, exactly as the document stated it, or nil. legibility
        /// never synthesizes one.
        public var title: String?
        /// Authors and the published date the document declared, joined for
        /// display. Nil when it declared neither.
        public var byline: String?
        /// A link submission with no body of its own — a Hacker News or Reddit
        /// post that is a headline plus an outbound URL. Rendering it as an empty
        /// article would read as a failure, so the caller renders the link.
        public var isLinkOnly: Bool
        /// The outbound URL on a link submission.
        public var linkURL: URL?
        /// legibility's own 0–10000 ranking score. Not a probability and not
        /// calibrated; useful only for ordering, or for a threshold you choose.
        public var confidence: Int
        /// The engine stopped at its output limit, so the body is short of the page.
        public var truncated: Bool
        /// How many comments the page carried, which is not always how many came
        /// back in `comments` — see `ReaderCommentThread.missing`.
        public var commentCount: Int
        /// The page's discussion, or nil when it had none.
        public var comments: ReaderCommentThread?
    }

    /// Which engine build the bundled page carries, once it has loaded. Worth
    /// surfacing in a diagnostic: a stale module looks exactly like a fix that
    /// did not work.
    public private(set) var build: String?

    /// Extracts from a serialized document.
    ///
    /// `document` should be the outer HTML of a page whose media and link URLs
    /// have already been made absolute — legibility resolves nothing relative,
    /// having no base URL to resolve against.
    public func extract(document: String, timeout: TimeInterval = 12) async -> Outcome {
        guard !document.isEmpty else { return .noArticle(reason: "NoTextContent") }
        await acquire()
        defer { release() }

        // Cancelled while queued. `defer` has already passed the baton on, so the
        // next caller starts immediately instead of waiting out a parse of a document
        // nobody will look at — which is what made a third parser switch queue behind
        // two abandoned ones.
        if Task.isCancelled { return .unavailable }

        guard let webView = await readyWebView() else { return .unavailable }

        switch await call(on: webView, document: document, timeout: timeout) {
        case .failed:
            // A trapped wasm instance stays trapped — the module is built with
            // `panic = abort`, so every later call on this page would fail the
            // same way. Drop the page so the next extraction gets a fresh one.
            teardown()
            return .unavailable
        case .value(let json):
            extractionsOnThisPage += 1
            scheduleIdleTeardown()
            guard let json, let payload = await Self.decode(json) else { return .unavailable }
            return payload.outcome
        }
    }

    // MARK: - The page

    private var webView: WKWebView?
    private var loader: Loader?
    private var loadTask: Task<WKWebView?, Never>?
    private var idleTeardown: Task<Void, Never>?
    private var extractionsOnThisPage = 0
    /// Bumped by every teardown, so a load that started before it knows not to
    /// publish what it built.
    private var generation = 0

    /// wasm linear memory never shrinks once grown, so one very large page keeps
    /// costing that memory for the instance's whole life. Recycling bounds it
    /// without paying re-instantiation on every article.
    private static let extractionsBeforeRecycling = 50
    /// Reading is bursty: a handful of articles, then nothing. Holding a web view
    /// and a compiled module through the nothing is what this avoids.
    private static let idleSeconds: TimeInterval = 90

    /// How many comments to carry back from a thread.
    ///
    /// Not a display limit — the reader pages through what it gets — but a bound on
    /// what crosses out of the web view and gets stored. A front-page discussion runs
    /// to a thousand replies, and the reader renders each body through the native HTML
    /// parser, so the whole thread is neither cheap to move nor cheap to draw. What is
    /// left out is reported rather than hidden.
    static let maxComments = 250

    private func readyWebView() async -> WKWebView? {
        idleTeardown?.cancel()
        idleTeardown = nil
        if extractionsOnThisPage >= Self.extractionsBeforeRecycling { teardown() }
        if let webView { return webView }
        if let loadTask { return await loadTask.value }

        let task = Task { @MainActor [weak self] in
            await self?.load() ?? nil
        }
        loadTask = task
        let result = await task.value
        loadTask = nil
        return result
    }

    private func load() async -> WKWebView? {
        guard let url = Bundle.module.url(forResource: "Legibility", withExtension: "html") else {
            return nil
        }
        let startedAt = generation

        let configuration = WKWebViewConfiguration()
        // Deliberately NOT `WebViewWarmer`'s pool or data store. That pool is
        // shared with web views that load real article pages; this one parses
        // hostile markup and belongs in its own process with no cookies, no
        // localStorage, and nothing to leak into or out of.
        configuration.websiteDataStore = .nonPersistent()
        configuration.defaultWebpagePreferences.allowsContentJavaScript = true

        // Zero-sized: nothing here is ever displayed, and legibility lays nothing
        // out — it is handed a string and returns a string.
        let webView = WKWebView(frame: .zero, configuration: configuration)
        let loader = Loader()
        webView.navigationDelegate = loader
        self.loader = loader

        // `loadFileURL` rather than `loadHTMLString`: the page's `null` file origin
        // is what its CSP was written against. Read access is bounded to the one
        // file and not to its directory — the page has no need of anything else in
        // the resource bundle, and this is the page in which attacker-controlled
        // markup gets parsed. Its own `default-src 'none'` should not be the only
        // thing standing there.
        webView.loadFileURL(url, allowingReadAccessTo: url)

        guard await loader.value(timeoutAfter: 20) == true, startedAt == generation else {
            webView.navigationDelegate = nil
            return nil
        }

        // Compile the module now rather than inside the first extraction, and read
        // the build stamp while we are in there. A one-tag document is the
        // cheapest input that still forces `WebAssembly.instantiate`.
        let stamp = await call(
            on: webView,
            script: "await window.legibility.extract('<p>x</p>'); return String(window.legibility.build);",
            arguments: [:],
            timeout: 20)
        guard case .value(let value) = stamp, let value, startedAt == generation else {
            webView.navigationDelegate = nil
            return nil
        }
        build = value

        self.webView = webView
        extractionsOnThisPage = 0
        return webView
    }

    private func teardown() {
        idleTeardown?.cancel()
        idleTeardown = nil
        // A load in flight must not publish its web view afterwards. Without this, a
        // teardown during the 900 KB page load plus module instantiation — the peak
        // window, and the likeliest moment to be asked to free memory — tore down
        // nothing and then reinstated the page it had just dropped.
        loadTask?.cancel()
        loadTask = nil
        generation &+= 1
        if let webView {
            webView.stopLoading()
            webView.navigationDelegate = nil
        }
        webView = nil
        loader = nil
        extractionsOnThisPage = 0
    }

    private func scheduleIdleTeardown() {
        idleTeardown?.cancel()
        idleTeardown = Task { @MainActor [weak self] in
            try? await Task.sleep(for: .seconds(Self.idleSeconds))
            guard !Task.isCancelled else { return }
            self?.teardown()
        }
    }

    // MARK: - Calling in

    /// What a call into the page came back with. An `Error` would be the natural
    /// shape, but `Error` is not `Sendable` and this value crosses a task boundary
    /// — and nothing here acts on *which* failure it was, only that there was one.
    private enum CallResult: Sendable {
        case value(String?)
        case failed
    }

    private func call(
        on webView: WKWebView,
        document: String,
        timeout: TimeInterval
    ) async -> CallResult {
        await call(on: webView, script: Self.extractScript, arguments: ["source": document], timeout: timeout)
    }

    /// Runs `script` and gives up after `timeout`.
    ///
    /// A wedged web content process cannot be interrupted from here — WebKit has
    /// no cancellation for an in-flight evaluation — so the timeout is the caller
    /// stopping the wait, not the work. That is enough: the reader falls back to
    /// the other parser, and the page is torn down afterwards.
    private func call(
        on webView: WKWebView,
        script: String,
        arguments: [String: Any],
        timeout: TimeInterval
    ) async -> CallResult {
        let gate = Once<CallResult>()
        Task { @MainActor in
            do {
                let value = try await webView.callAsyncJavaScript(
                    script, arguments: arguments, contentWorld: .page)
                gate.settle(.value(value as? String))
            } catch {
                gate.settle(.failed)
            }
        }
        Task { @MainActor in
            try? await Task.sleep(for: .seconds(timeout))
            gate.settle(.failed)
        }
        return await gate.value(timeoutAfter: nil) ?? .failed
    }

    /// A one-shot value several tasks may race to set and one task awaits.
    ///
    /// `@MainActor`, so "several tasks" never means "at the same time" — the
    /// settle-once check needs no lock, only the guarantee that both racers run on
    /// the same actor.
    @MainActor
    private final class Once<Value: Sendable> {
        private var settled: Value?
        private var waiting: CheckedContinuation<Value?, Never>?

        func settle(_ value: Value) {
            guard settled == nil else { return }
            settled = value
            let continuation = waiting
            waiting = nil
            continuation?.resume(returning: value)
        }

        /// Awaits the value. `timeoutAfter` is a convenience for callers with no
        /// other racer to lose to; nil waits indefinitely.
        func value(timeoutAfter seconds: TimeInterval?) async -> Value? {
            if let settled { return settled }
            if let seconds {
                Task { @MainActor [weak self] in
                    try? await Task.sleep(for: .seconds(seconds))
                    self?.expire()
                }
            }
            return await withCheckedContinuation { (continuation: CheckedContinuation<Value?, Never>) in
                if let settled {
                    continuation.resume(returning: settled)
                } else {
                    waiting = continuation
                }
            }
        }

        /// Resumes an unsettled waiter with nothing, so a timeout is a `nil`
        /// answer rather than a task that never returns.
        private func expire() {
            guard settled == nil, let continuation = waiting else { return }
            waiting = nil
            continuation.resume(returning: nil)
        }
    }

    /// Waits for the page's first navigation to finish.
    @MainActor
    private final class Loader: NSObject, WKNavigationDelegate {
        private let once = Once<Bool>()

        func value(timeoutAfter seconds: TimeInterval) async -> Bool? {
            await once.value(timeoutAfter: seconds)
        }

        func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            once.settle(true)
        }

        func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
            once.settle(false)
        }

        func webView(
            _ webView: WKWebView,
            didFailProvisionalNavigation navigation: WKNavigation!,
            withError error: Error
        ) {
            once.settle(false)
        }
    }

    // MARK: - One extraction at a time

    // The module is a single instance in a single JS realm, and one large document
    // already costs the instance its peak memory for good. Overlapping calls
    // cannot corrupt each other — JavaScript is single-threaded and the wasm call
    // is synchronous — but they would stack two documents' worth of linear memory
    // to no benefit, so they queue.
    private var busy = false
    private var waiting: [CheckedContinuation<Void, Never>] = []

    private func acquire() async {
        guard busy else {
            busy = true
            return
        }
        await withCheckedContinuation { (continuation: CheckedContinuation<Void, Never>) in
            waiting.append(continuation)
        }
    }

    private func release() {
        if waiting.isEmpty {
            busy = false
        } else {
            waiting.removeFirst().resume()
        }
    }

    // MARK: - The call, and what comes back

    /// Projects legibility's canonical JSON down to the fields Nook renders, in
    /// the page rather than in Swift. The full document carries every comment on
    /// the page and a byte span for every metadata candidate; bridging all of that
    /// out of the web view to throw most of it away would be the expensive part of
    /// an otherwise fast extraction.
    private static let extractScript = """
    const d = await window.legibility.extract(source);
    const m = d.metadata || {};
    const c = d.comments || {};
    const items = c.items || [];
    const value = (c) => (c && typeof c.value === 'string' && c.value.trim()) ? c.value.trim() : null;
    const published = m.published || null;

    // A comment body wrapped in table markup is the forum's layout, not the
    // comment's content — Hacker News nests a table per reply. Unwrapping the cells
    // keeps the text and drops a grid the reader would otherwise draw around every
    // comment. Done here, where there is a DOM to do it in, rather than with a
    // regular expression on the native side.
    const LAYOUT = new Set(['TABLE', 'TBODY', 'THEAD', 'TFOOT', 'TR', 'TD', 'TH', 'COLGROUP', 'COL']);
    function unwrapLayout(html) {
      if (!html || html.indexOf('<t') === -1) return html;
      try {
        const holder = document.createElement('div');
        holder.innerHTML = html;
        // Bounded: a malicious body could nest thousands of tables, and this runs on
        // every comment of every article.
        for (let pass = 0; pass < 12; pass += 1) {
          const found = holder.querySelectorAll('table, tbody, thead, tfoot, tr, td, th, colgroup, col');
          if (!found.length) break;
          found.forEach(function (node) {
            if (!LAYOUT.has(node.tagName)) return;
            while (node.firstChild) node.parentNode.insertBefore(node.firstChild, node);
            node.remove();
          });
        }
        return holder.innerHTML;
      } catch (_) {
        return html;
      }
    }
    return JSON.stringify({
      // `title_without_site_name` is populated only when the site-name suffix was
      // confirmed against `og:site_name`, so it is the better title when present —
      // and it is absent far more often than not.
      title: value(m.title_without_site_name) || value(m.title),
      authors: (m.authors || []).map(value).filter(Boolean),
      published: published ? (published.raw || published.iso8601 || null) : null,
      noArticle: d.no_article || null,
      article: d.article ? {
        html: d.article.html || '',
        text: d.article.text || '',
        kind: d.article.kind || 'article',
        url: d.article.url || null,
        confidence: d.article.confidence || 0,
        truncated: !!d.article.truncated,
      } : null,
      commentCount: (d.comments && d.comments.count) || 0,
      claimedTotal: c.completeness ? (c.completeness.claimed_total ?? null) : null,
      commentsTruncated: !!(c.completeness && c.completeness.truncated),
      depthSource: c.depth_source || null,
      // A prefix, not a sample: `parent` is an index into this array and a parent
      // always precedes its reply, so keeping the first N keeps every kept item's
      // parent with it. `commentCount` and `claimedTotal` still say what the page
      // had, so the reader can report what it is not showing instead of implying
      // the thread ends here.
      comments: items.slice(0, \(LegibilityEngine.maxComments)).map(function (it, i) {
        return {
          i: i,
          a: (it.author && it.author.trim()) || null,
          t: (it.timestamp && it.timestamp.trim()) || null,
          d: it.depth || 0,
          p: (typeof it.parent === 'number') ? it.parent : null,
          l: it.permalink || null,
          x: !!it.deleted,
          s: it.text || '',
          h: unwrapLayout(it.html || ''),
        };
      }),
    });
    """

    /// Decodes off the main actor.
    ///
    /// The payload carries the whole article as HTML and again as text, so on a long
    /// piece this is a few hundred kilobytes of UTF-8 copy plus a JSON parse — and it
    /// lands inside the window the reader perceives as the switch, on the same thread
    /// that just serialized the source document across IPC.
    nonisolated private static func decode(_ json: String) async -> Payload? {
        await Task.detached(priority: .userInitiated) {
            try? JSONDecoder().decode(Payload.self, from: Data(json.utf8))
        }.value
    }

    private struct Payload: Decodable, Sendable {
        struct Article: Decodable {
            var html: String
            var text: String
            var kind: String
            var url: String?
            var confidence: Int
            var truncated: Bool
        }

        var title: String?
        var authors: [String]
        var published: String?
        var noArticle: String?
        var article: Article?
        var comments: [ReaderComment]
        var commentCount: Int
        var claimedTotal: Int?
        var commentsTruncated: Bool
        var depthSource: String?

        /// The discussion, or nil when the page had none worth drawing.
        var thread: ReaderCommentThread? {
            let usable = comments.filter { $0.renderableHTML != nil || $0.isDeleted }
            guard !usable.isEmpty else { return nil }
            return ReaderCommentThread(
                items: usable, count: commentCount, claimedTotal: claimedTotal,
                isTruncated: commentsTruncated || usable.count < commentCount,
                depthSource: depthSource)
        }

        var outcome: Outcome {
            guard let article else { return .noArticle(reason: noArticle) }
            let byline = [authors.joined(separator: ", "), published ?? ""]
                .filter { !$0.isEmpty }
                .joined(separator: " · ")
            return .article(
                Extraction(
                    html: article.html,
                    text: article.text,
                    title: title,
                    byline: byline.isEmpty ? nil : byline,
                    isLinkOnly: article.kind == "discussion-root",
                    linkURL: article.url.flatMap(URL.init(string:)),
                    confidence: article.confidence,
                    truncated: article.truncated,
                    commentCount: commentCount,
                    comments: thread))
        }
    }
}
